mainApp/accounts/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('login/', views.login_view, name="login"),
    path('register/', views.register_view, name="register"),
    path('logout/', views.logout_view, name="logout") 
]

mainApp/project_track/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from . import settings

urlpatterns = [
    path('', RedirectView.as_view(url='/projects_app')),
    path('admin/', admin.site.urls),
    path('projects_app/', include("projects_app.urls")),
    path('accounts/', include("accounts.urls"))
]

if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    from django.conf.urls.static import static

    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(
        settings.DOCUMENT_URL, document_root=settings.DOCUMENT_ROOT)
    urlpatterns += static(
            settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainApp/projects_app/urls.py
from django.urls import path, include
from . import views

# list views ------------------------------------------------------------------------------------
urlpatterns = [
    path("", views.ProjectListView.as_view(), name="projects"),
    path('customers/', views.CustomerListView.as_view(), name="customers"),
    path('domains/', views.DomainListView.as_view(), name="domains"),
    path('objectives/', views.ObjectiveListView.as_view(), name="objectives"),
    # path('projects/', views.ProjectListView.as_view(), name="projects"),
    path('workitems/', views.workitem_list_view, name="workitems"), 
    path('init', views.init),
]


# Customer views ------------------------------------------------------------------------------------
urlpatterns += [
    path('customer/<int:pk>', views.CustomerDetailView.as_view(), name='customer-detail'),
    path('customer/add', views.CustomerCreateView.as_view(), name='customer-add'),
    path('customer/update/<int:pk>', views.CustomerUpdateView.as_view(), name='customer-update'),
    path('customer/delete/<int:pk>', views.CustomerDeleteView.as_view(), name='customer-delete'),
]

# Objective views ------------------------------------------------------------------------------------
urlpatterns += [
    path('objective/<int:pk>', views.ObjectiveDetailView.as_view(), name='objective-detail'),
    path('objective/add', views.ObjectiveCreateView.as_view(), name='objective-add'),
    path('objective/update/<int:pk>', views.ObjectiveUpdateView.as_view(), name='objective-update'),
    path('objective/delete/<int:pk>', views.ObjectiveDeleteView.as_view(), name='objective-delete'),
]

# Domain views ------------------------------------------------------------------------------------
urlpatterns += [
    path('domain/<int:pk>', views.DomainDetailView.as_view(), name='domain-detail'),
    path('domain/add', views.DomainCreateView.as_view(), name='domain-add'),
    path('domain/update/<int:pk>', views.DomainUpdateView.as_view(), name='domain-update'),
    path('domain/delete/<int:pk>', views.DomainDeleteView.as_view(), name='domain-delete'),
]

# Workitem views ------------------------------------------------------------------------------------
urlpatterns += [
    path('workitem/<int:pk>', views.WorkItemDetailView.as_view(), name='workitem-detail'),
    path('workitem/add', views.WorkItemCreateView.as_view(), name='workitem-add'),
    path('workitem/update/<int:pk>', views.WorkItemUpdateView.as_view(), name='workitem-update'),
    path('workitem/delete/<int:pk>', views.WorkItemDeleteView.as_view(), name='workitem-delete'),
]

# Project views ------------------------------------------------------------------------------------
urlpatterns += [
    path('project/add', views.ProjectCreateView.as_view(), name='project-add'),
    path('project/<int:project_id>/', views.project, name='project'),
    path('project/<int:project_id>/<int:workitem_id>', views.project_workitems, name='project-workitems'),
    path('project/addworkitem/<int:pk>', views.project_addworkitem, name="project-update-workitems"),
    path('project/progress/<int:project_id>', views.project_progress, name = "project-progress"),
    path('project/delete/<int:pk>', views.ProjectDeleteView.as_view(), name = "project-delete"),
    path('project/update/<int:pk>/', views.ProjectUpdateView.as_view(), name='project-edit'),
    path('project/<int:project_id>/<int:workitem_id>/<int:message_id>', views.retrieve_file, name='retrieve-file'),
    path('project/adduserpage/<int:pk>/', views.add_user_page, name='project-add-user-page'),
    path('project/adduser/<int:pk>/', views.add_user, name='project-add-user'),
    path('project/removeuser/<int:pk>/<int:uk>/', views.remove_user, name='project-remove-user'),
    path('project/status/<int:pk>', views.ProjectStatusUpdateView.as_view(), name='project-status'),
    path('project/domaintable/<int:pk>/<int:uk>/', views.domain_table, name='project-domain-table'),
    path('project/domaintable/addcolumn/<int:pk>/<int:uk>/', views.add_table_column, name='project-add-column'),
    path('project/domaintable/addrow/<int:pk>/<int:uk>/', views.add_table_row, name='project-add-row'),
]

# Auth views ------------------------------------------------------------------------------------
from django.contrib.auth import views as auth_views
urlpatterns += [
    path('accounts/login/' ,auth_views.LoginView.as_view(), name='login'),
]

# Generate proposal view

urlpatterns += [
    path('project/<int:pk>/genpro/', views.generateProposal, name='genproposal'),
    path('project/<int:pk>/geneng/', views.generateEngagement, name='genengagement')
]

mainApp/projects_app/models.py
from django.contrib import admin
from django.db import models
from datetime import datetime
from django.urls import reverse
from django.contrib.auth import (
    get_user_model
)

User = get_user_model()
# Create your models here.

class Objective(models.Model):
    description = models.CharField(max_length=165, default='')
    def __str__(self):
        return self.description
    class Meta:
        verbose_name = ("Objective")
        verbose_name_plural = ("Objectives")
    def get_absolute_url(self):
        return reverse("objective-detail", kwargs={"pk": self.pk})

class Customer(models.Model):
    name = models.CharField(max_length=35, blank=True, default='', verbose_name="Customer name")
    address1 = models.CharField(max_length=55, blank=True, default='', verbose_name = "Address 1")
    address2 = models.CharField(max_length=55, blank=True, default='', verbose_name = "Address 2")
    city = models.CharField(max_length=35, blank=True, default='', verbose_name="City")

    class Meta:
        verbose_name = ("Customer")
        verbose_name_plural = ("Customers")
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("customer-detail", kwargs={"pk": self.pk})

class Domain(models.Model):
    description = models.CharField(max_length=140, default='')
    # this manytomanyfield not required
    # workitems = models.ManyToManyField('WorkItem', blank=True)
    def __str__(self):
        return self.description
    class Meta:
        verbose_name = ("Domain")
        verbose_name_plural = ("Domains")
    def get_absolute_url(self):
        return reverse("domain-detail", kwargs={"pk": self.pk})
    class Admin: pass

class WorkItem(models.Model):
    description = models.CharField(max_length=180, default='')
    indomain = models.ForeignKey(Domain, on_delete=models.CASCADE, default=1)
    def __str__(self):
        return "{}/{}".format(self.indomain.description,self.description)
    class Admin: pass
    def get_absolute_url(self):
        return reverse("workitem-detail", kwargs={"pk": self.pk})

class Project(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, default=1)
    objectives = models.ManyToManyField(Objective, blank=True)
    proposaldate = models.DateField(default=datetime.now, verbose_name="Proposal Date")
    startdate = models.DateField(default=datetime.now, verbose_name="Start Date")
    enddate = models.DateField(default=datetime.now, verbose_name="End Date")
    domains = models.ManyToManyField(Domain, blank=True)
    workitems = models.ManyToManyField(WorkItem, blank=True)
    fees = models.IntegerField(default=0)
    feesaftergrant = models.IntegerField(default=0, verbose_name="Fees after grant")
    billing1 = models.CharField(max_length=50, default="30% upon appointment of our services", verbose_name="First Billing")
    billing2 = models.CharField(max_length=50, default="60% upon issuance of draft report", verbose_name="Second Billing")
    billing3 = models.CharField(max_length=50, default="10% upon issuance of follow up report", verbose_name="Final Billing")
    proptemplate = models.CharField(max_length=50, default='sample.pptx')
    engatemplate = models.CharField(max_length=50, default='sample.docx')
    users = models.ManyToManyField(User, blank=True)
    
    PROP = "PROPOSAL"
    IP = "IN_PROGRESS"
    EN = "ENDED"

    status_choice = (
        (PROP, "Proposal"),
        (IP, "In progress"),
        (EN, "Ended"),
    )

    status = models.CharField(max_length=20, choices=status_choice, default=PROP)

    def __str__(self):
        return self.customer.name+self.proposaldate.strftime(":%Y-%m-%d")

    def get_absolute_url(self):
        return reverse("project", kwargs={"project_id": self.pk})
    class Admin: pass

#class MyModelAdmin(admin.ModelAdmin):
#    def formfield_for_manytomany(self, db_field, request, **kwargs):
#        if db_field.name == "cars":
#            kwargs["queryset"] = Car.objects.filter(owner=request.user)
#        return super(MyModelAdmin, self).formfield_for_manytomany(db_field, request, **kwargs)

class Message(models.Model):

    name = models.CharField(max_length=100)
    description = models.CharField(max_length=300, help_text="Enter description of document")
    date_added = models.DateTimeField(auto_now=False, auto_now_add=True)

    document_file = models.FileField(upload_to = "document", max_length=100, null=True, blank=True)
    workitem_name = models.ForeignKey(WorkItem, on_delete=models.CASCADE)
    project_id = models.ForeignKey(Project, on_delete=models.CASCADE)
    
    class Meta:
        verbose_name = ("Document")
        verbose_name_plural = ("Documents")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("message-detail", kwargs={"pk": self.pk})

class TableDictionary(models.Model):
    project_id = models.ForeignKey(Project, on_delete=models.CASCADE)
    domain_id = models.ForeignKey(Domain, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, default="")

    class Meta:
        verbose_name = ("Table")
        verbose_name_plural = ("Tables")

    def __str__(self):
        return self.name
    class Admin: pass

class KeyValue(models.Model):
    table_dictionary = models.ForeignKey(TableDictionary, on_delete=models.CASCADE)
    key = models.CharField(max_length=240, default="")
    value = models.CharField(max_length=240, default="")

mainApp/projects_app/forms.py
from django import forms
from .models import Customer, Project
import datetime
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

class DateInput(forms.DateInput):
    input_type = 'date'

class ProjectForm(forms.ModelForm):

    # proposal_date = forms.DateField(widget=DateInput, required=False)

    class Meta:
        model = Project
        fields = ("customer", 'objectives', 'domains' , 'proposaldate', 'startdate', 'enddate','fees','feesaftergrant','billing1','billing2','billing3')
        widgets = {
            'objectives': forms.CheckboxSelectMultiple,
            'domains': forms.CheckboxSelectMultiple,
            'proposaldate': forms.SelectDateWidget,
            'startdate': forms.SelectDateWidget,
            'enddate': forms.SelectDateWidget,
        }
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save'))

        
class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ("name", 'address1', 'address2', 'city')

class ProjectStatusForm(forms.ModelForm):
    
    class Meta:
        model = Project
        fields = ("status",)
        widgets = {
            'status':forms.RadioSelect,
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save'))

mainApp/projects_app/templates/projects_app/project/edit.html
{% extends 'base.html' %}

{% comment %} NOT IN USE CURRENTLY {% endcomment %}
{% block content %}
<h1 class="h1">Project {{ project.id }}</h1>
<form method='post'>{% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Save">
</form>
{% endblock content %}

mainApp/projects_app/templates/projects_app/project/project.html
{% extends 'base.html' %}
{% load my_filters %}

{% block header %}
<div class="container pt-3">
<div class="bs-stepper">
  <div class="bs-stepper-header">
    <div class="step {% if project.status == 'PROPOSAL' %}active{% endif %}">
        <a href=" {% url 'project-status' project.id %} ">
        <span class="bs-stepper-circle">1</span>
        <span class="bs-stepper-label">Proposal</span>
      </a>
    </div>
    <div class="line"></div>
    <div class="step {% if project.status == 'IN_PROGRESS' %}active{% endif %}" >
      <a href=" {% url 'project-status' project.id %} ">
        <span class="bs-stepper-circle">2</span>
        <span class="bs-stepper-label">In progress</span>
      </a>
    </div>
    <div class="line"></div>
    <div class="step {% if project.status == 'ENDED' %}active{% endif %}" >
    <a href=" {% url 'project-status' project.id %} ">
        <span class="bs-stepper-circle">3</span>
        <span class="bs-stepper-label">Ended</span>
      </a>
    </div>
  </div>
</div>
</div>




{% endblock header %}


{% block content %}
<h1 class="h1">Project #{{ project.id }} 
    {% comment %} <span style="float:right" class="h5" >
        Status: <a href=" {% url 'project-status' project.id %} ">{{project.get_status_display}}</a>
    </span> {% endcomment %}
</h1>

<table class="table table-striped table-sm">
    <tr>
        <td><strong>Customer</strong></td>
        <td>{{ project.customer }}
            
        </td>
    </tr>
    <tr>
        <td><strong>Address</strong></td>
        <td>
            {{ project.customer.address1 }}
            <br>{{ project.customer.address2 }}
        </td>
    </tr>
    <tr>
        <td><strong>Proposal Date</strong></td>
        <td>{{project.proposaldate}}</td>
    </tr>
    <tr>
        <td><strong>Start Date</strong></td>
        <td>{{project.startdate}}</td>
    </tr>
    <tr>
        <td><strong>End Date</strong></td>
        <td>{{project.enddate}}</td>
    </tr>
    <tr>
        <td><strong>Fees</strong></td>
        <td>{{ project.fees|currency }}</td>
    </tr>
    <tr>
        <td><strong>Fees after grant</strong></td>
        <td>{{ project.feesaftergrant|currency }}</td>
    </tr>
    <tr>
        <td><strong>Billing 1</strong></td>
        <td>{{project.billing1}}</td>
    </tr>
    <tr>
        <td><strong>Billing 2</strong></td>
        <td>{{project.billing2}}</td>
    </tr>
    <tr>
        <td><strong>Billing 3</strong></td>
        <td>{{project.billing3}}</td>
    </tr>
</table>
<hr>

<h2>Objectives</h2>
<ul>
    {% for objective in objective_list %}
        <li>
            {{objective}} 
        </li>
    {% endfor %}
</ul>
<hr>

<h2>Domains and Work Items</h2>
    <ul>
    {% for dom in domain_list %}
        <li>
            <a href="{% url 'project-domain-table' pk=project.id uk=dom.id %}">
            <i class="fa fa-table" ></i>
            </a>
            {{ dom }}
        </li>
          <ul>
            {% for w in workitem_list %}
                {% if dom == w.indomain %}
                    <li>{{ w.description }}</li>
                {% endif %}
            {% endfor %}
          </ul>
    {% endfor %}
    </ul>
<hr>

{% if project.status == 'PROPOSAL' %}
<a class="btn btn-outline-dark" href = "{% url 'project-edit' project.id %}" role = "button">Edit project details</a>
<a href=" {% url 'project-update-workitems' project.id %} " class="btn btn-outline-dark mt-2 mb-2">Edit work items</a>

{% if request.user.is_superuser %}
<a href="{% url 'project-add-user-page' project.id %}" class="btn btn-outline-dark">Access rights</a>
{% endif %}
<hr>
{% endif %}


<h2>Downloads</h2>
<a href=" {% url 'genproposal' project.id%} " class="btn btn-outline-dark" role="button" >Generate proposal document</a>
<a href=" {% url 'genengagement' project.id%} " class="btn btn-outline-dark" role="button" >Generate engagement document</a>

{% endblock content %}

mainApp/projects_app/templates/projects_app/project/project_add_user.html
{% extends 'base.html' %}

{% block content %}
<h1 class="h1">Project {{ project.id }}'s access rights</h1>
<br>

<h2>Authorized users</h2>
<ul>
{% for user in user_list %}
    <li style="padding-bottom:7px;">
        {{user}} <a href = "{% url 'project-remove-user' pk=project.id uk=user.id %}" class="btn btn-outline-danger btn-sm">Remove user</a><br>
    </li>
{% empty %}
</ul>
    There are currently no authorized users
<ul>
{% endfor %}
</ul>
<hr>

{% if addable_users %}

<button class="collapsible">Add User</button><br>

<div class="addUser" id="addUser">
    <br>
    <b>Select a user below to authorize viewing the project</b>
    <br>
    <br>
    <form method=POST action="{% url 'project-add-user' project.id %}">{% csrf_token %}
        <select id="added_user" name="added_user">
            {% for user in addable_users %}
                <option value="{{user.id}}">
                {{user}}
                </option>
            {% endfor %}
        </select><br><br>
        <input class="btn btn-outline-dark" type="submit" value="Submit">
    </form>
</div>
{% else %}
<b>There are no more users to add</b>
{% endif %}

<script>    
    var coll = document.getElementsByClassName("collapsible");
    var i;

    for (i = 0; i < coll.length; i++) {
    coll[i].addEventListener("click", function() {
        this.classList.toggle("active");
        var content = document.getElementById("addUser");
        if (content.style.maxHeight){
        content.style.maxHeight = null;
        } else {
        content.style.maxHeight = content.scrollHeight + "px";
        }
    });
    }
</script>

<style>
    .collapsible {
    background-color: #eee;
    color: #444;
    cursor: pointer;
    padding: 9px;
    border: none;
    text-align: left;
    outline: none;
    font-size: 15px;
    }

    .active, .collapsible:hover {
    background-color: #ccc;
    }

    .addUser {
    overflow: hidden;
    background-color: white;
    max-height: 0;
    transition: max-height 0.2s ease-out;
    }
</style>

{% endblock content %}

mainApp/projects_app/templates/projects_app/project/project_add_workitem.html
{% extends 'base.html' %}

{% block content %}
<h2>Add work items into Project {{project}} </h2>
<hr>
<form method='POST'>{% csrf_token %}
<input type="hidden" name="project" value={{project.id}}>
{% for domain in domains %}
    <div class="form-check">
        <h4>{{domain}}</h4>
        {% for workitem in workitems %}
            {% if workitem.indomain == domain %}
                {% if workitem in current_workitems %}
                <input type="checkbox" class="form-check-input" value="1" name= "{{workitem.description}}" checked>
                {% else %}
                <input type="checkbox" class="form-check-input" value="1" name= "{{workitem.description}}">
                {% endif %}
                {{workitem.description}}
                <br>
            {% endif %}
        {% endfor %}
    </div>
    <hr>
{% endfor %}
</table>
<button type="submit" class="btn btn-primary">Save project</button> 



</form>

{% endblock content %}

mainApp/projects_app/templates/projects_app/project/project_delete.html
{% extends 'base.html' %}

{% block content %}
<h1 class="h1">Deleting a project</h1>
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock content %}

mainApp/projects_app/templates/projects_app/project/project_domain_table.html
{% extends 'base.html' %}

{% block content %}
<h1 class="h1">Project {{ project.id }}'s user table</h1>

<!-- if there are messages show display it -->
{% if messages %}
  <br>
  {% for message in messages %}
  {% if message.tags == 'error' %}
  <div class="alert alert-danger" id="message">
  {% else %}
  <div class="alert alert-{{ message.tags }}" id="message">
  {% endif %}
    {{ message }}
  </div>
  {% endfor %}
{% endif %}
<br>

{% if columnlist %}
<form id="form" method="POST" action="{% url 'project-domain-table' pk=project.id uk=uk %}">{% csrf_token %}
<table id="user-table" class="table table-bordered table-responsive">

  <thead>
    <tr id="columns">
    {% for item in columnlist %}
      <th scope="col">
        {{item}}
      </th>
    {% endfor %}
    </tr>
  </thead>
  <tbody>
  {% for row in rowlists %}
    <tr>
        {% for value in row %}
        <td>
            <input name="{{forloop.parentloop.counter}},{{forloop.counter0}}" class="input" type="text" value="{{value}}">
        </td>
        {% endfor %}
    </tr>
  {% endfor %}
  </tbody>

</table>

<button type="submit" class="btn btn-primary">Save table</button>
</form>
{% else %}
There is currently no user table here. Try adding some columns first.
{% endif %}
<hr>

<button class='collapsible btn btn-outline-dark'>Add column</button>

{% if project.status == 'PROPOSAL' %}
{% else %}
{% if columnlist %}
<a href=" {% url 'project-add-row' pk=project.id uk=uk %} " class="btn btn-outline-dark">Add row </a>
{% endif %}
{% endif %}

<div class="textArea" id="textArea"><br>
  <form id="new_column" method="POST" action="{% url 'project-add-column' pk=project.id uk=uk %}">{% csrf_token %}
    Please specify a name for the new column below<br><br>
    Column Name: <input name="column_name" type='text'><br><br>
    
    <button type="submit" class="btn btn-outline-dark">Confirm</button>
  </form>
<hr>
</div>
<script>    
  var coll = document.getElementsByClassName("collapsible");
  var i;

  for (i = 0; i < coll.length; i++) {
  coll[i].addEventListener("click", function() {
      this.classList.toggle("active");
      var content = document.getElementById("textArea");
      if (content.style.maxHeight){
      content.style.maxHeight = null;
      } else {
      content.style.maxHeight = content.scrollHeight + "px";
      }
  });
  }


</script>


<style>

.input {
    border:none;
}

.table-responsive{
  display: inline-table;
}

.textArea {
  overflow: hidden;
  background-color: white;
  max-height: 0;
  transition: max-height 0.2s ease-out;
}

</style>

{% endblock content %}

mainApp/projects_app/templates/projects_app/project/project_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h1 class="h1">Project details</h1>
<form method='post'>
    {% csrf_token %}
    {{form.customer|as_crispy_field}}

    {{form.objectives|as_crispy_field}}

    {{form.domains|as_crispy_field}}

    <div class="row">
        <div class="col-4">
            {{form.proposaldate|as_crispy_field}}
        </div>

        <div class="col-4">
            {{form.startdate|as_crispy_field}}
        </div>

        <div class="col-4">
            {{form.enddate|as_crispy_field}}
        </div>
    </div>

    <div class="row">
        <div class="col-6">
            {{form.fees|as_crispy_field}}
        </div>
        <div class="col-6">
            {{form.feesaftergrant|as_crispy_field}}
        </div>
    </div>

    <div class="row">
        <div class="col-4">
            {{form.billing1|as_crispy_field}}
        </div>

        <div class="col-4">
            {{form.billing2|as_crispy_field}}
        </div>

        <div class="col-4">
            {{form.billing3|as_crispy_field}}
        </div>
    </div>

    <button type="submit" class="btn btn-primary">Save project</button>
</form>
{% endblock content %}

mainApp/projects_app/templates/projects_app/project/project_messages.html
{% extends 'base.html' %}

{% block content %}
<h1 class="h1">Project #{{ project.id }}</h1>
<h5>Customer name: {{ project.customer }}</h5>
<a class="btn btn-outline-dark" href="{% url 'projects' %}">Project list</a>
<a class="btn btn-outline-dark" href="{% url 'project-progress' project.id %}">Project progress</a><br><br>
Domain: {{workitem.indomain}}<br>
Description: {{workitem.description}}<br><br>
{% if project.status != "ENDED" %}
<button class="collapsible">Add Message</button><br>

<div class="textArea" id="textArea">
<form enctype="multipart/form-data" method=POST action="{% url 'project-workitems' project_id=project.id workitem_id=wid %}">{% csrf_token %}    

<textarea class="form-control" id="messageText" name="messageText" placeholder="New message here..." rows="5" cols="50">
</textarea><br>
<input type="file" id="document_file" name="document_file"><br><br>
<input class="btn btn-outline-dark" type="submit" value="Submit">

</form>
</div>
{% endif %}

<hr>
<h1 class="h1">Messages</h1>

{% if message_list %}
<table class="table table-striped">
    {% for message in message_list %}
    <tr>
        <td>
        <b>#</b>{{forloop.revcounter}}
        <br/>
        <b>Posted:</b> {{message.date_added}}
        <br/>
        <b>Posted by:</b> {{message.name}}
        <br/>
        {{message.description}}
        <br/>
        {% if message.document_file %}
            <b>Files:</b> <a href="{{message.document_file.url}}" download>{{message.document_file}}</a>
        {% endif %}
        </td>
    </tr>
    {% endfor %}
</table>
{% else %}
    <p>There are no messages for this workitem in the database yet.</p>
{% endif %}

<script>    
    var coll = document.getElementsByClassName("collapsible");
    var i;

    for (i = 0; i < coll.length; i++) {
    coll[i].addEventListener("click", function() {
        this.classList.toggle("active");
        var content = document.getElementById("textArea");
        if (content.style.maxHeight){
        content.style.maxHeight = null;
        } else {
        content.style.maxHeight = content.scrollHeight + "px";
        }
    });
    }
</script>

<style>
    .collapsible {
    background-color: #eee;
    color: #444;
    cursor: pointer;
    padding: 9px;
    border: none;
    text-align: left;
    outline: none;
    font-size: 15px;
    }

    .active, .collapsible:hover {
    background-color: #ccc;
    }

    .textArea {
    overflow: hidden;
    background-color: white;
    max-height: 0;
    transition: max-height 0.2s ease-out;
    }
</style>
{% endblock content %}

mainApp/projects_app/templates/projects_app/project/project_progress.html
{% extends 'base.html' %}

{% block content %}
<h1 class="h1">Project #{{ project.id }}</h1>
<h5>Customer: {{ project.customer }}</h5>
<hr>
<h2>Messages</h2>

    {% if workitem_list|length > 0 %}
    {% for domain in domain_list %}
    <h5>{{domain.description}}</h5>
      {% for key, value in domain_message_dict.items %}
      <!-- {{key}} : {{value}} -->
      {% if key.description == domain.description %}
      <small>Total number of messages: {{value.0}}</small>
      <br/><small>Last Posted: {{value.1}}</small>
      <hr>
      {% endif %}
      {% endfor %}
      <ul>
        {% for i1,i2 in my_list %}
        <!-- i1 is workitem list, i2 is messagelist -->
            {% if i1.indomain == domain %}
            <li>
                <a href="{% url 'project-workitems' project_id=project.id workitem_id=forloop.counter %}">{{i1.description}}</a> 
                {% if i2.0 > 0 %}
                    <br/><small>Number of messages: {{i2.0}}</small>
                    <br/><small>Last Posted: {{i2.1}}</small>
                  {% else %}
                    <br/><small>Number of messages: 0</small>
                    <br/><small>Last Posted: - </small>
                {% endif %}
            </li>
           {% endif %}
        {% endfor %}
      </ul>
    {% endfor %}
    {% endif %}
    
{% endblock content %}

mainApp/projects_app/templates/projects_app/project/project_status.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<h1>Changing project status</h1>
 <form method='post'>
    {% csrf_token %}
    {{form|crispy}}
<button type="submit" class="btn btn-primary">Submit</button>
</form>


{% endblock content %}